services:
  - type: web
    runtime: docker
    name: zenith-server
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false # jdbc:postgresql://<host>.neon.tech:5432/<dbname>?sslmode=require
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
