services:
  - type: web
    runtime: docker
    name: zenith-server
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
