spring.application.name=zenith
server.port=${PORT:3000}

# Database
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/zenith}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false