spring.application.name=zenith
server.port=${PORT:3000}

# Database (Neon PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-rough-tree-aigyn5to-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_uWj0d6NPvKDz}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false